{
     "button":[
     {	
          "type":"click",
          "name":"今日歌曲",
          "key":"V1001_TODAY_MUSIC"
      },
      {
           "type":"click",
           "name":"歌手简介",
           "key":"V1001_TODAY_SINGER"
      },
      {
           "name":"菜单",
           "sub_button":[
           {	
               "type":"view",
               "name":"搜索",
               "url":"http://www.soso.com/"
            },
            {
               "type":"view",
               "name":"视频",
               "url":"http://v.qq.com/"
            },
            {
               "type":"click",
               "name":"赞一下我们",
               "key":"V1001_GOOD"
            }]
       }]
 }


{
     "button":[
     {	
          "type":"click",
          "name":"定水果",
          "key":"order"
      },
      {
           "name":"订单", 
            "sub_button":[
                   {"type":"view","name":"个人中心","url":""},
                   {"type":"view","name":"我的订单","url":""}
            ]
      },
      {
           "name":"商家合作",
           "sub_button":[
           {	
               "type":"view",
               "name":"我的店铺",
               "url":""
            },
            {
               "type":"view",
               "name":"合作热线",
               "url":""
            }
       }]
 }